name: SISPS-EXP-SOH
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - openpyxl
  - tabulate
  - opencv
  - pip
  - pip:
      - darkdetect
      - import_ipynb
      - matplotlib-label-lines
